### ISSUE TITLE
h5 is deprecated

### ISSUE THREAD

**Issue by jeroen** [sg4r/rblt#8]
The `h5` package on which you depend has a [deprecation notice](https://github.com/mannau/h5#deprecation-notice):

> as of October 25th the h5 package is officially deprecated in favor of the hdf5r package. hdf5r is more feature complete than h5 while having less design flaws (e.g. no C++ API). hdf5r also includes most of h5's API which should make the transition for existing h5 users easier. We would therefore strongly suggest to switch to hdf5r ASAP.

The h5 package has some serious problems. Would you consider moving to hdf5r?

**Comment by sg4r** [comment]
thank this  message.
i have fix and use hdf5r package

**Comment by jeroen** [comment]
Can you please submit the new package to CRAN?

**Comment by sg4r** [comment]
yes,  i submit as rblt 0.2.4.5 ;)
